In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


Creating Tensors


In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix=torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim


3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random Tensors

In [ ]:
#create a random tensor of sixze(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9213, 0.9511, 0.7883, 0.5919],
        [0.5401, 0.6093, 0.3555, 0.3695],
        [0.8719, 0.2665, 0.0650, 0.6535]])

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [ ]:
first=torch.arange(start=0,end=1000,step=77)
first

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
few_zeros=torch.zeros_like(input=first)
few_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensors Datatype

In [ ]:
float_32_tensors=torch.tensor([3.,6,9],
                              dtype=None,
                              device=None,#what devie is your tensor on
                              requires_grad=False)

float_32_tensors

tensor([3., 6., 9.])

In [ ]:
float_32_tensors.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensors.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensors

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensors*int_32_tensor

tensor([ 9., 36., 81.])

Getting information from tensors

In [ ]:
some_tensor=torch.rand(size=(3,4))
some_tensor

tensor([[0.1043, 0.7424, 0.2949, 0.7555],
        [0.3481, 0.0312, 0.1396, 0.1416],
        [0.2761, 0.9658, 0.1538, 0.2352]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")##can also use some_tensor.size()--size is a function not an attribute
print(f"Device tensor is on: {some_tensor.device}" )


tensor([[0.1043, 0.7424, 0.2949, 0.7555],
        [0.3481, 0.0312, 0.1396, 0.1416],
        [0.2761, 0.9658, 0.1538, 0.2352]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
###Manipulating Tensors
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

Matrix Multiplication(Dot Product)


In [ ]:
%%time
torch.matmul(tensor,tensor)#can also use torch.mm

CPU times: user 208 µs, sys: 38 µs, total: 246 µs
Wall time: 1.26 ms


tensor(14)

In [ ]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

In [ ]:
tensor_B_T=tensor_B.T
tensor_B_T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
print(f"Multiplying:{tensor_A.shape}*{tensor_B_T.shape}<-inner dimension match\n")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B_T)
print(output)

Multiplying:torch.Size([3, 2])*torch.Size([2, 3])<-inner dimension match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


Reshaping,Viewing,Stacking,Squeezing and Unsqueezing

In [ ]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped=x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
z=x.view(9,1)
z

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
#Changing z changes x as both share same memory
z[0]=5
z,x

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=1)#dim=0-->vstack
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_squeezed=x_reshaped.squeeze()#removes all single dimensions
x_squeezed,x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Permuting
x_original=torch.rand(size=(224,224,3))
x_permuted=x_original.permute(2,0,1)
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


Indexing


In [ ]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th & 1st dimension but only index 1 of second dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of 0th dimension but only 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

Pytorch and Numpy

In [ ]:
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)#when coverting from numpy to pytorch pytorch reflects numpy's datatype unless specified
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
array=array+1
array,tensor#Tensor wont change

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()#Default datatype of numpy--float64 pytorch--float32
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility

In [ ]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.2606, 0.4361, 0.0223, 0.1457],
        [0.2398, 0.7068, 0.2586, 0.5971],
        [0.2638, 0.3442, 0.1980, 0.0898]])
tensor([[0.6102, 0.6181, 0.3648, 0.1412],
        [0.2130, 0.8386, 0.9567, 0.2187],
        [0.3863, 0.7438, 0.9274, 0.2749]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Lets make some randombut reproducible tensors
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Sun Oct  1 10:24:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()

1

Putting tensors on the GPU

In [ ]:
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to gpu if available
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Moving tensors back to the CPU\

In [ ]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])